# Generated by Django 5.1.3 on 2024-11-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicular_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicularrequest',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
