# Generated by Django 5.1.3 on 2024-11-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicular_requests', '0002_vehicularrequest_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicularrequest',
            name='status',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10),
        ),
    ]
