# Generated by Django 5.1.3 on 2024-11-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicular_requests', '0003_vehicularrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicularrequest',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
