# Generated by Django 5.1.3 on 2024-12-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicular_requests', '0005_alter_vehicularrequest_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicularrequest',
            name='request_type',
            field=models.CharField(choices=[('persona', 'Persona'), ('vehiculo', 'Vehiculo')], default='vehiculo', max_length=10),
        ),
    ]
