# Generated by Django 5.1.3 on 2024-12-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicular_requests', '0006_vehicularrequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicularrequest',
            name='person_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicularrequest',
            name='person_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicularrequest',
            name='plate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicularrequest',
            name='serial_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
