# Generated by Django 5.1.3 on 2024-12-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicular_requests', '0007_vehicularrequest_person_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicularrequest',
            name='request_type',
        ),
    ]
