# Generated by Django 5.1.3 on 2024-12-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicular_requests', '0009_persona_analista_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='numero_serie',
            field=models.CharField(default='00000', max_length=20, unique=True),
        ),
    ]
