# Generated by Django 5.1.3 on 2024-12-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicular_requests', '0010_vehiculo_numero_serie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='placa',
            new_name='plate',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='numero_serie',
            new_name='serial_number',
        ),
    ]
