# Generated by Django 5.1.3 on 2024-12-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicular_requests', '0011_rename_placa_vehiculo_plate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='serial_number',
            new_name='numero_serie',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='plate',
            new_name='placa',
        ),
    ]
