# Generated by Django 5.1.3 on 2024-12-01 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicular_requests', '0013_persona_edad_persona_nacionalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nomina', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencias',
            fields=[
                ('request_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('colonia', models.CharField(max_length=255)),
                ('policia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='vehicular_requests.policia')),
            ],
        ),
    ]
